GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlciI6IkJvYiIsImlhdCI6MTcxNTg3NTU5NCwiZXhwIjoxNzE1ODc2NDk0fQ.MPL8Eep-kfLk0pByFacPQANi8M5fq0QaoLoGHR8ywYA


###
POST http://localhost:4000/token
Content-Type: application/json

{
	"token": "Bob"
}


###
POST http://localhost:4000/login
Content-Type: application/json

{
	"name": "Bob"
}


### 

GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3MTU4Njk5NDcsImV4cCI6MTcxNTk1NjM0N30.NjgdwifejBuQvJfJkKJI60Bzt7p1TkW0ORwtceTo3dY

